<?php

namespace Altgeek\OeuvreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreRepository extends EntityRepository
{
}
